
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Example.Models.Shared
{
    using Newtonsoft.Json;
    
    public class Error
    {

        [JsonProperty("code")]
        public int Code { get; set; } = default!;

        [JsonProperty("message")]
        public string Message { get; set; } = default!;
    }
}